const arcanes = [
  {
    id: "00",
    title: "O Louco",
    src: "img/maiores/00.jpg",
    advc: "É hora de ter coragem e iniciar o que você deseja fazer",
  },
  {
    id: "01",
    title: "O Mago",
    src: "img/maiores/01.jpeg",
    advc: "Você tem o poder de resolver as questões, mas é preciso agir",
  },
  {
    id: "02",
    title: "A Sacerdotisa",
    src: "img/maiores/02.jpeg",
    advc: "A intuição é a maior aliada agora, tenha confiança nela",
  },
  {
    id: "03",
    title: "A Imperatriz",
    src: "img/maiores/03.jpeg",
    advc: "Cuide e nutra, suas ações devem sempre levar em conta aqueles que você ama",
  },
  {
    id: "04",
    title: "O Imperador",
    src: "img/maiores/04.jpeg",
    advc: "As vezes é preciso um pouco mais de rigidez para organizar tudo, não tenha medo",
  },
  {
    id: "05",
    title: "O Hierofante",
    src: "img/maiores/05.jpeg",
    advc: "Não é hora de invenção, tome a atitude mais normal e corriqueira, o que já foi testado é mais segudo",
  },
  {
    id: "06",
    title: "Os Enamorados",
    src: "img/maiores/06.jpeg",
    advc: "Suas escolhas geram consequências que serão de sua responsabilidade. Tenha maturidade de assumir",
  },
  {
    id: "07",
    title: "O Carro",
    src: "img/maiores/07.jpeg",
    advc: "É preciso sair do lugar e seguir adiante, mas se prepare antes para enfrentar os perigos do caminho",
  },
  {
    id: "08",
    title: "A Força",
    src: "img/maiores/08.jpeg",
    advc: "Querer não é DEVER, sua razão deve, neste momento, ser maior que seu instinto e seus desejos",
  },
  {
    id: "09",
    title: "O Eremita",
    src: "img/maiores/09.jpeg",
    advc: "Busque a sabedoria de quem já chegou lá, hora de sentar e aprender",
  },
  {
    id: "10",
    title: "A Roda da Fortuna",
    src: "img/maiores/10.jpeg",
    advc: "Às vezes e cima, às vezes embaixo, prepare-se para uma mudança na posição",
  },
  {
    id: "11",
    title: "A Justiça",
    src: "img/maiores/11.jpg",
    advc: "Colhemos o que plantamos, esta é a hora da colheita",
  },
  {
    id: "12",
    title: "O Pendurado",
    src: "img/maiores/12.jpg",
    advc: "Algumas vezes a única alternativa que temos é tentar observar por um outro ponto de vista e aprender com a experiência",
  },
  {
    id: "13",
    title: "A Morte",
    src: "img/maiores/13.jpg",
    advc: "Tudo ocupa espaço e é preciso retirar o velho para dar lugar ao novo",
  },
  {
    id: "14",
    title: "A Temperança",
    src: "img/maiores/14.jpg",
    advc: 'O caminho do equilíbrio é o mais indicado para ser seguido. "Nem tanto ao céu, nem tanto à terra"',
  },
  {
    id: "15",
    title: "O Diabo",
    src: "img/maiores/15.jpg",
    advc: "Nem sempre a melhor escolha é a mais elevada, um pouco de prazer não irá te matar, mas não se torne escravo dele",
  },
  {
    id: "16",
    title: "A Torre",
    src: "img/maiores/16.jpg",
    advc: "Não há segurança em nada que você acredita ser seguro. Reavalie tudo antes que desmorone sobre você",
  },
  {
    id: "17",
    title: "A Estrela",
    src: "img/maiores/17.jpg",
    advc: "Por pior que seja a situação, há sempre uma luz no fim túnel, mas você seve caminhar pela escuridão",
  },
  {
    id: "18",
    title: "A Lua",
    src: "img/maiores/18.jpg",
    advc: "Suspeite das verdades estabelecidas para você, há muita ilusão no caminho",
  },
  {
    id: "19",
    title: "O Sol",
    src: "img/maiores/19.jpg",
    advc: "A iluminação está presente no caminho, vitória e sucesso se apresentam, mas cuidado com a arrogância",
  },
  {
    id: "20",
    title: "O Julgamento",
    src: "img/maiores/20.jpg",
    advc: "Antes de renascer, é importante avaliar o que foi feito antes, só assim a nova criatura não cometerá os mesmos erros",
  },
  {
    id: "21",
    title: "O Mundo",
    src: "img/maiores/21.jpg",
    advc: "É preciso concluir processos, admitir que eles se encerraram",
  },
];
